{% set name = "plotly" %}
{% set version = "4.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b6ad5c3d2cbf056a782e3c6833a334c45a5453a12dc8a48df971602509e8d3d6

build:
  number: 1
  noarch: python

requirements:
  build:
    - python
    - nodejs
    - pip
  run:
    - python
    - setuptools
    - retrying >=1.3.3
    - six
  run_constrained:
    - nodejs
    - jupyterlab >=2

test:
  requires:
    - pip
  commands:
    - pip check
    - test -f $PREFIX/share/jupyter/lab/extensions/js/jupyterlab-{{ name }}-{{ version }}.tgz  # [unix]
  imports:
    - plotly

about:
  home: https://plot.ly/python/
  license: MIT
  license_file: LICENSE.txt
  summary: An interactive, browser-based graphing library for Python
  description: |
    Plotly's Python graphing library makes interactive,
    publication-quality graphs online. Examples of how to make line
    plots, scatter plots, area charts, bar charts, error bars, box plots,
    histograms, heatmaps, subplots, multiple-axes, polar charts and
    bubble charts.
  doc_url: https://plot.ly/python/
  dev_url: https://github.com/plotly/plotly.py

extra:
  recipe-maintainers:
    - chohner
    - moorepants
    - ocefpaf
