{% set version = "3.4.0" %}

package:
  name: plotly
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/plotly/plotly-{{ version }}.tar.gz
  sha256: 7e08fb1cb4b2c01f8c469816ae19707fcb4f4aaeef5305966eabf147569805df

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - decorator >=4.0.6
    - nbformat >=4.2
    - pytz
    - requests
    - retrying >=1.3.3
    - six

test:
  imports:
    - plotly

about:
  home: https://plot.ly/python/
  license: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: 'An interactive, browser-based graphing library for Python'
  description: |
    Plotly's Python graphing library makes interactive,
    publication-quality graphs online. Examples of how to make line
    plots, scatter plots, area charts, bar charts, error bars, box plots,
    histograms, heatmaps, subplots, multiple-axes, polar charts and
    bubble charts.
  doc_url: https://plot.ly/python/
  dev_url: https://github.com/plotly/plotly.py

extra:
  recipe-maintainers:
    - chohner
    - moorepants
    - ocefpaf
